// GENERATED by scripts/extract-math-constants.mjs from STIX Two Math's OpenType
// MATH table — do not edit by hand. Values are fractions of the em (font size),
// multiplied by the font size at layout time (see mathFont.ts).

export interface StixMathConstants {
  axisHeight: number;
  ruleThickness: number;
  scriptPercent: number;
  scriptScriptPercent: number;
  fracNumShiftUp: number;
  fracDenShiftDown: number;
  fracNumGapMin: number;
  fracDenGapMin: number;
  supShiftUp: number;
  supShiftUpCramped: number;
  subShiftDown: number;
  supSubGapMin: number;
  spaceAfterScript: number;
  upperLimitGapMin: number;
  upperLimitBaselineRiseMin: number;
  lowerLimitGapMin: number;
  lowerLimitBaselineDropMin: number;
  stackGapMin: number;
  radicalVerticalGap: number;
  radicalRuleThickness: number;
  radicalExtraAscender: number;
  radicalKernBeforeDegree: number;
  radicalKernAfterDegree: number;
  radicalDegreeRaise: number;
  overbarVerticalGap: number;
  overbarRuleThickness: number;
  overbarExtraAscender: number;
  underbarVerticalGap: number;
  accentBaseHeight: number;
  displayOperatorMinHeight: number;
  delimitedSubFormulaMinHeight: number;
  mathLeading: number;
}

export const STIX_MATH_CONSTANTS: StixMathConstants = {
  "axisHeight": 0.258,
  "ruleThickness": 0.068,
  "scriptPercent": 0.7,
  "scriptScriptPercent": 0.55,
  "fracNumShiftUp": 0.585,
  "fracDenShiftDown": 0.585,
  "fracNumGapMin": 0.068,
  "fracDenGapMin": 0.068,
  "supShiftUp": 0.36,
  "supShiftUpCramped": 0.252,
  "subShiftDown": 0.21,
  "supSubGapMin": 0.15,
  "spaceAfterScript": 0.04,
  "upperLimitGapMin": 0.135,
  "upperLimitBaselineRiseMin": 0.3,
  "lowerLimitGapMin": 0.135,
  "lowerLimitBaselineDropMin": 0.67,
  "stackGapMin": 0.15,
  "radicalVerticalGap": 0.085,
  "radicalRuleThickness": 0.068,
  "radicalExtraAscender": 0.078,
  "radicalKernBeforeDegree": 0.065,
  "radicalKernAfterDegree": -0.335,
  "radicalDegreeRaise": 0.55,
  "overbarVerticalGap": 0.175,
  "overbarRuleThickness": 0.068,
  "overbarExtraAscender": 0.068,
  "underbarVerticalGap": 0.175,
  "accentBaseHeight": 0.48,
  "displayOperatorMinHeight": 1.8,
  "delimitedSubFormulaMinHeight": 1.325,
  "mathLeading": 0.15
};
